apiVersion: apps/v1
kind: Deployment
metadata:
  name: weops-prometheus
  labels:
    app: weops-prometheus
spec:
  selector:
    matchLabels:
      app: weops-prometheus
  template:
    metadata:
      labels:
        app: weops-prometheus
    spec:
      serviceAccount: {{ .Release.Name }}-kube-state-metrics
      containers:
      - name: prometheus
        env:
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--enable-feature=agent"
          - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
          - "--storage.agent.wal-compression"
          - "--storage.agent.retention.min-time=30s"
          - "--storage.agent.retention.max-time=5m"
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /opt/bitnami/prometheus/conf/prometheus.yml
          subPath: ./prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: weops-prometheus-config
          items:
          - key: prometheus.yml
            path: ./prometheus.yml