apiVersion: apps/v1
kind: Deployment
metadata:
  name: weops-flow
  labels:
    app: weops-flow
spec:
  selector:
    matchLabels:
      app: weops-flow
  template:
    metadata:
      labels:
        app: weops-flow
    spec:
      serviceAccount: {{ .Release.Name }}-kube-state-metrics
      containers:
      - name: grafana-agent-flow
        env:
        - AGENT_MODE: flow
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "run"
        - "/etc/agent/flow.yaml"
        ports:
          - containerPort: 12345
        volumeMounts:
        - name: agent-config
          mountPath: /etc/agent/flow.yaml
          subPath: ./flow.yml
      volumes:
      - name: agent-config
        configMap:
          name: weops-flow-config
          items:
          - key: flow.yml
            path: ./flow.yml