apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
{{ toYaml .Values.labels | indent 8 }}
      name: {{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.ports.external }}'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        # node-exporter 只监听 localhost
        - name: {{ .Chart.Name }}
          image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          args:
            - --path.procfs=/host-proc
            - --path.sysfs=/host-sys
            - --path.rootfs={{ .Values.filesystem.rootMount.mountPath }}
            - --collector.filesystem.ignored-mount-points={{ .Values.filesystem.ignoredMountPoints | quote }}
            - --web.listen-address=127.0.0.1:{{ .Values.ports.internal }}
          volumeMounts:
            - name: proc
              mountPath: /host-proc
              readOnly: true
            - name: sys
              mountPath: /host-sys
              readOnly: true
            - name: filesystem-root
              mountPath: {{ .Values.filesystem.rootMount.mountPath }}
              readOnly: true
{{ range .Values.filesystem.mounts }}
{{ if .enabled }}
            - name: filesystem-{{ .name }}
              mountPath: {{ $.Values.filesystem.rootMount.mountPath }}{{ .mountPath }}
              readOnly: true
{{ end }}
{{ end }}
        # nginx sidecar 过滤 pprof
        - name: metrics-filter
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.ports.external }}
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: filesystem-root
          hostPath:
            path: {{ .Values.filesystem.rootMount.hostPath }}
            type: Directory
{{ range .Values.filesystem.mounts }}
{{ if .enabled }}
        - name: filesystem-{{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
{{ end }}
{{ end }}
        - name: nginx-config
          configMap:
            name: node-exporter-nginx-config
      hostNetwork: true
      hostPID: true
